# Generated by Django 2.2 on 2021-11-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_post',
            name='description',
            field=models.TextField(),
        ),
    ]
